### ISSUE TITLE
`points(Ultraspherical(1, -1..1), n)` returns points on Chebyshev grid of the first kind and not the second kind

### ISSUE THREAD

**Issue by Luapulu** [JuliaApproximation/ApproxFunOrthogonalPolynomials.jl#62]
```Julia
using ApproxFunOrthogonalPolynomials

# For reference
chebyshevpoints(Float64, 3, Val(1))  # [0.866, 0.0, -0.866]
chebyshevpoints(Float64, 3, Val(2))  # [1.0, 0.0, -1.0]

# These should be points corresponding to the Chebyshev polynomials of the second kind, I thought?
points(Ultraspherical(1, -1..1), 3)  # [0.866, 0.0, -0.866]
```

**Comment by dlfivefifty** [comment]
Not necessarily since we compute the coefficients by first computing the Chebyshev T coefficinets:

https://github.com/JuliaApproximation/ApproxFunOrthogonalPolynomials.jl/blob/9d9e0930f160ece0f196f0858e1b9c4819db124b/src/Spaces/Ultraspherical/Ultraspherical.jl#L44

**Comment by Luapulu** [comment]
So to calculate coefficients for the Chebyshev coefficients of the second kind, I should evaluate my function on points corresponding to Chebyshev polynomials of the first kind?

**Comment by dlfivefifty** [comment]
Yes. Why not?

**Comment by dlfivefifty** [comment]
Note we do have a `chebyshevutransform` that isn't currently used:

https://github.com/JuliaApproximation/FastTransforms.jl/blob/bc83208bb9e9bb0b77babd12ad7cace3869ee312/src/chebyshevtransform.jl#L224

A PR might make sense... I just don't see why it would matter that much.

**Comment by Luapulu** [comment]
Oh ok. There's no problem. I just didn't know it worked that way and it seemed odd at first. I guess the `points` function doesn't represent the various grids belonging to the corresponding polynomial types but instead represents exactly those points needed to calculate the transform in question.
